### PR TITLE
Fix main menu on small devices (Fixes #2005)

### LINKED ISSUE #2005: Fix main menu on small devices (in responsive design)
The responsive design of web interface has to fixed that in small window sizes (e.g. small devices) the main menu is clickable. Currently it's still broken.

### PR DESCRIPTION
**Pull request by emanuelschuetze**
Use bootstraps navbar-toggle button to bring up a
vertical responsive main menu.
Some additional responsive CSS impmprovements.

### CODE REVIEW

File: openslides/core/static/js/core/site.js [hunk 1]
```diff
@@ -437,6 +437,10 @@ angular.module('OpenSlidesApp.core.site', [
     'mainMenu',
     function ($scope, mainMenu) {
         mainMenu.registerScope($scope);
+        $scope.isMenuOpen = false;
+        $scope.closeMenu = function () {
+            $scope.isMenuOpen = false;
+        }
```
Comment (normanjaeckel) [inline openslides/core/static/js/core/site.js]: Travis failed because of missing semicolon. Run `gulp jshint` to see this.

**Comment by normanjaeckel** [comment]
One error. Rest is ok.

**Comment by emanuelschuetze** [comment]
Travis fixed. Rebased. Ready for merge.
