### PR TITLE
Use a whitelist for getFormOrStateForCurrentSlide (fixes #3112, #3038)

### LINKED ISSUE #3112: Bug Unkown provider PromptFormProvider
On start voting w/ the VoteCollector this error occurs:

Error: [$injector:unpr] Unknown provider: PromptFormProvider <- PromptForm
http://errors.angularjs.org/1.5.8/$injector/unpr?p0=PromptFormProvider%20%3C-%20PromptForm
    at angular.js:71
    at angular.js:4514
    at Object.getService [as get] (angular.js:4667)
    at angular.js:4519
    at Object.getService [as get] (angular.js:4667)
    at Object.fromCollectionString (base.js:1071)
    at base.js:818
    at Object.forEach (angular.js:338)
    at Coreprojector.getFormOrStateForCurrentSlide (base.js:804)
    at fn0 (eval at compile (angular.js:14820), <anonymous>:4:624)
(anonymous) @ angular.js:13923
(anonymous) @ angular.js:10470
$digest @ angular.js:17545
$apply @ angular.js:17793
tick @ angular.js:12640

My temporay solution:
https://github.com/jwinzer/OpenSlides/blob/voting-1/openslides/core/static/js/core/base.js#L811

See #3064

### PR DESCRIPTION
**Pull request by emanuelschuetze**
- Provided csv header fields as meta data while csv import (#3038).
- Consolidate (already translated) strings for motion poll.
- Fixed typos for MotionPoll model.

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
This pullrequest replaced #3064

File: openslides/core/static/js/core/base.js [hunk 1]
```diff
@@ -819,11 +819,13 @@ angular.module('OpenSlidesApp.core', [
                                 id: value.id,
                             };
                         } else if (
-                            value.name != 'agenda/item-list' &&
-                            value.name != 'core/clock' &&
-                            value.name != 'core/countdown' &&
-                            value.name != 'core/projector-message' &&
-                            value.name != 'agenda/current-list-of-speakers' ) {
+                            value.name === 'agenda/item' ||
```
Comment (normanjaeckel) [inline openslides/core/static/js/core/base.js]: Ok, but please insert a comment here and a GitHub issue that we do not want to hardcode the apps in core here but implement a generic solution later (not for 2.1 of course).

Comment (emanuelschuetze) [inline openslides/core/static/js/core/base.js]: Done.
