### PR TITLE
Watch perms in client (closes #1855)

### LINKED ISSUE #1855: Autoupdate after changing user permissions does not work
e.g. user gets chat permission -> should show chat link without reload

### PR DESCRIPTION
**Pull request by FinnStutzenstein**
Every base view now has a base permission. Currently by entering for example `/users/` the users were shown also without the `can_see_name` permission.

Whats with the projector permissions? Now everyone can see the projector, also if the user has not the `can_see_projector` permission.

### CODE REVIEW

File: openslides/assignments/static/js/assignments/site.js [hunk 1]
```diff
@@ -34,6 +34,7 @@ angular.module('OpenSlidesApp.assignments.site', [
                 template: "<ui-view/>",
                 data: {
                     title: gettext('Elections'),
+                    basePerm: 'assignmentss.can_see',
```
Comment (normanjaeckel) [inline openslides/assignments/static/js/assignments/site.js]: Typo.

File: openslides/core/static/js/core/site.js [hunk 2]
```diff
@@ -114,10 +114,18 @@ angular.module('OpenSlidesApp.core.site', [
...
     'gettextCatalog',
-    function ($rootScope, gettextCatalog) {
+    'operator',
+    function ($rootScope, gettextCatalog, operator) {
         $rootScope.activeAppTitle = '';
-        $rootScope.$on('$stateChangeSuccess', function(evt, toState) {
-            $rootScope.activeAppTitle = toState.data ? toState.data.title : '';
+        $rootScope.$on('$stateChangeSuccess', function(event, toState) {
+            if (toState.data) {
+            $rootScope.activeAppTitle = toState.data.title || '';
```
Comment (normanjaeckel) [inline openslides/core/static/js/core/site.js]: Indention is broken.

File: openslides/core/static/js/core/site.js [hunk 3]
```diff
@@ -286,6 +295,7 @@ angular.module('OpenSlidesApp.core.site', [
                 controller: 'ManageProjectorsCtrl',
                 data: {
                     title: gettext('Manage projectors'),
+                    basePerm: 'core.can_manage_projectors',
```
Comment (normanjaeckel) [inline openslides/core/static/js/core/site.js]: Typo.

File: openslides/core/static/js/core/start.js [hunk 4]
```diff
@@ -30,6 +30,40 @@ angular.module('OpenSlidesApp.core.start', [])
...
+        $rootScope.$watch(function () {
+            return Group.lastModified();
+        }, function () {
+            if (Group.getAll().length) {
+                permissionChangeCallback();
+            }
+        });
+
+        $rootScope.$watch(function () {
+            return operator.user ? User.lastModified(operator.user.id) : true;
```
Comment (normanjaeckel) [inline openslides/core/static/js/core/start.js]: This watcher is partly redundant with operator.setUser method that we call in line 25. Maybe the setUser method should be removed.

File: openslides/core/static/js/core/site.js (hunk 3 above)
Comment (FinnStutzenstein) [inline openslides/core/static/js/core/site.js]: Done.

File: openslides/core/static/js/core/site.js (hunk 2 above)
Comment (FinnStutzenstein) [inline openslides/core/static/js/core/site.js]: Done.

File: openslides/assignments/static/js/assignments/site.js (hunk 1 above)
Comment (FinnStutzenstein) [inline openslides/assignments/static/js/assignments/site.js]: Done.

File: openslides/core/static/js/core/start.js (hunk 4 above)
Comment (FinnStutzenstein) [inline openslides/core/static/js/core/start.js]: I think we need the setUser method, but the permissions does not have to be set in this method because the watcher does this now.

**Comment by FinnStutzenstein** [comment]
@normanjaeckel Ping.

**Comment by emanuelschuetze** [comment]
I'll add a CHANGELOG entry and rebase it now that I can merge it today...

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze If I'm fast enough, I'll make it now ;)

**Comment by FinnStutzenstein** [comment]
@emanuelschuetze Done.

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Great, thanks!
