### PR TITLE
Fix osPerms to use groups registered and anonymous

### LINKED ISSUE #1586: 'os-perms' does not check the default groups (anonymous/registered)
The directive `os-perms="agenda.can_see"` does not work for the admin who is in staff and registered group. Because the permission "agenda.can_see" is selected in group Registered only. For "agenda.can_mange" (permission from staff group) it works as expected.

Please add also all permissions from the default groups (registered/anonymous) to allPerms in getPerms function in users.js. Then we can use "os-perms" correctly in template (e.g. show menu item "agenda" only if users have at least "agenda.can_see" permission.

### PR DESCRIPTION
**Pull request by ostcar**
Fixes #1586

### CODE REVIEW

File: openslides/users/static/js/users/users.js [hunk 1]
```diff
@@ -42,27 +42,12 @@ angular.module('OpenSlidesApp.users', [])
                 }
                 return name;
             },
-            get_full_name: function() {
```
Comment (emanuelschuetze) [inline openslides/users/static/js/users/users.js]: Why you removed this function?

Comment (ostcar) [inline openslides/users/static/js/users/users.js]: See line 27 of the file

Comment (emanuelschuetze) [inline openslides/users/static/js/users/users.js]: Ok.

File: openslides/users/views.py [hunk 2]
```diff
@@ -110,11 +111,22 @@ def check_permissions(self, request):
         permission to see users and in case of create, update or destroy
         requests the permission to see extra user data and to manage users.
         """
-        if (not request.user.has_perm('users.can_see_name') or
-                (self.action in ('create', 'update', 'destroy') and not
-                 (request.user.has_perm('users.can_manage') and
-                  request.user.has_perm('users.can_see_extra_data')))):
-            self.permission_denied(request)
+        # Any logged in user can retrive groups.
```
Comment (normanjaeckel) [inline openslides/users/views.py]: Hm. I don't like this style (using multiple returns in a difficult function). We can merge this for now but I would like to refactor all permission checks later. May be we should use explicit permission checks in the view methods instead of the general method `check_permission`.

File: openslides/users/views.py [hunk 3]
```diff
@@ -110,11 +111,22 @@ def check_permissions(self, request):
...
+        # Anonymous user can retrive groups when they are activated.
+        if (self.action in ('retrieve', 'list') and
+                (config['general_system_enable_anonymous'] or
+                 self.request.user.is_authenticated())):
+            return
+
+        # Users with the permissions 'can_manage' and 'can_see_extra_data' can
+        # edit groups.
+        if (self.action in ('create', 'update', 'destroy', 'partial_update') and
+                request.user.has_perm('users.can_manage') and
```
Comment (normanjaeckel) [inline openslides/users/views.py]: Please add `request.user.has_perm('users.can_see_name')` just for consistency. We will have to remove this later when we refactor the permission system using inheritance.

**Comment by normanjaeckel** [comment]
One remark, then merge.

File: openslides/users/views.py (hunk 3 above)
Comment (ostcar) [inline openslides/users/views.py]: done with protest
